import { PatientRecord } from '@/app/doctor-dashboard/client';

export function generatePatientSummaryPDF(record: PatientRecord) {
  if (typeof window === 'undefined') return;

  const reportWindow = window.open('', '_blank');
  if (!reportWindow) return;

  const vitals = record.kiosk_data?.vitals;
  const triage = record.kiosk_data?.triage;
  const risk = record.kiosk_data?.risk_evaluation;

  const riskScore = record.risk_score || risk?.riskScore || 0;
  const triageLevel = record.triage_level || risk?.category || risk?.riskTier || 'EVALUATED';
  const department = record.department || triage?.department || 'General Practice';
  const age = record.age || record.kiosk_data?.age || 'N/A';

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Clinical Summary Report - ${record.patient_name}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 35px; color: #0f172a; line-height: 1.6; background: #fff; }
        .header { border-bottom: 2px solid #059669; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-start; }
        .title { font-size: 22px; font-weight: 800; color: #065f46; margin: 0; }
        .subtitle { font-size: 12px; color: #64748b; margin-top: 4px; }
        .badge { padding: 4px 10px; border-radius: 6px; font-weight: 700; font-size: 11px; text-transform: uppercase; }
        .badge-critical { background: #fee2e2; color: #991b1b; }
        .badge-normal { background: #d1fae5; color: #065f46; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 20px; }
        .card { padding: 14px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0; }
        .card-title { font-size: 11px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
        .card-body { font-size: 13px; color: #1e293b; margin: 0; }
        .disclaimer { margin-top: 30px; padding: 12px 16px; background: #fffbe3; border: 1px solid #fde047; border-radius: 8px; font-size: 11px; color: #713f12; }
        .btn-container { margin-top: 25px; text-align: right; }
        .btn { padding: 8px 18px; background: #059669; color: white; border: none; border-radius: 6px; font-weight: 700; cursor: pointer; font-size: 12px; }
        @media print { .btn-container { display: none; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <h1 class="title">MEDICOBOT Clinical Summary</h1>
          <p class="subtitle">Patient ID: ${record.id || 'N/A'} | Generated: ${new Date().toLocaleString()}</p>
        </div>
        <div>
          <span class="badge ${triageLevel === 'CRITICAL' ? 'badge-critical' : 'badge-normal'}">
            Triage: ${triageLevel}
          </span>
        </div>
      </div>

      <div class="grid">
        <div class="card">
          <div class="card-title">Patient Profile</div>
          <p class="card-body">
            <strong>Name:</strong> ${record.patient_name}<br/>
            <strong>Age / Sex:</strong> ${age} Yrs | ${record.kiosk_data?.sex || 'N/A'}<br/>
            <strong>Contact:</strong> ${record.phone_number || 'N/A'}<br/>
            <strong>Department:</strong> ${department}
          </p>
        </div>
        <div class="card">
          <div class="card-title">Follow-Up & Risk Status</div>
          <p class="card-body">
            <strong>Follow-Up Status:</strong> ${record.followUpStatus || 'Pending'}<br/>
            <strong>Risk Score:</strong> ${riskScore} / 100<br/>
            <strong>Vitals Summary:</strong> Temp ${vitals?.temperature || 98.6}°F | HR ${vitals?.heart_rate || 78} BPM | SpO2 ${vitals?.spo2 || 98}%
          </p>
        </div>
      </div>

      <div class="card" style="margin-bottom: 15px;">
        <div class="card-title">Reported Symptoms</div>
        <p class="card-body">${record.symptoms || 'No primary symptoms reported.'}</p>
      </div>

      <div class="card" style="margin-bottom: 15px;">
        <div class="card-title">Next-Step Guidance & AI Predictions</div>
        <p class="card-body">${triage?.summary || record.recommendations || record.ai_summary || 'Standard health monitoring recommended.'}</p>
      </div>

      <div class="card" style="margin-bottom: 15px;">
        <div class="card-title">Clinician Notes</div>
        <p class="card-body">${record.clinicianNote || 'No specific notes recorded by attending clinician.'}</p>
      </div>

      <div class="disclaimer">
        <strong>⚠️ OFFICIAL MEDICAL DISCLAIMER & NEXT-STEP GUIDANCE:</strong><br/>
        This document is an AI-assisted clinical summary generated by MEDICOBOT for triage reference only. It does not replace formal physician diagnostic evaluation. For urgent medical emergencies, immediately contact emergency health services or consult a licensed physician.
      </div>

      <div class="btn-container">
        <button onclick="window.print()" class="btn">🖨️ Print / Download PDF</button>
      </div>
    </body>
    </html>
  `;

  reportWindow.document.write(htmlContent);
  reportWindow.document.close();
}
